name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: python manage.py test

      - name: Run Integration Tests
        run: python manage.py test travel_itinerary_app.tests.integration_tests

      - name: Run End-to-End Tests
        run: python manage.py test tests.e2e_tests
