name: 'Terraform CI/CD'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Initialize
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      run: terraform init
      working-directory: terrformstuff

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: terrformstuff

    - name: Terraform Plan
      run: terraform plan
      working-directory: terrformstuff

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terrformstuff
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
